name: "Bambuddy Slicer API (Bambu Studio) (DEV)"
version: "02.07.01.62.8-1.2"
slug: bambuddy_bambu_studio_api_dev
image: "ghcr.io/connormxy/slicer-api-bambu-dev"
stage: experimental
description: "A headless Bambu Studio sidecar container for cloud-independent slicing in Bambuddy. (DEV)"
url: "https://github.com/connormxy/homeassistant-addon-bambuddy#dev"
arch:
  - amd64
startup: services
boot: auto
init: false
map:
  - share:rw
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Bambu Studio API Port (use this in Bambuddy settings)

healthcheck:
  enabled: true
  interval: 30s
  timeout: 5s
  retries: 3
