name: Builder

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.addon }} for ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        addon: ["bambuddy", "obico-ml-api", "slicer-api-bambu", "slicer-api-orca"]
        arch: ["aarch64", "amd64"]
        exclude:
          # Bambu Studio only builds for amd64
          - addon: "slicer-api-bambu"
            arch: "aarch64"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Get Add-on Version
        id: version
        shell: bash
        run: |
          VERSION=$(grep -E '^version: ' ${{ matrix.addon }}/config.yaml | awk '{print $2}' | tr -d '"'\''\r')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Build and Push
        uses: home-assistant/builder/actions/build-image@master
        with:
          arch: ${{ matrix.arch }}
          context: ${{ matrix.addon }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}-${{ matrix.arch }}
          image-tags: |
            ${{ steps.version.outputs.version }}
            latest
          push: "true"
          version: ${{ steps.version.outputs.version }}
